# server配置
server:
  port: 8800
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /

# spring配置
spring:
  application:
    name: core
# TODO 因为Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher。
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # 连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zhuzs?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: Root1234@

  # redis
  redis:
    #redis服务器地址
    host: localhost
    port: 6379
    password:
    database: 0
    #redis连接超时时间（毫秒）
    timeout: 18000
    #lettuce连接池配置 springboot2.x后默认使用Lettuce:
    #lettuce:
    jedis:
      pool:
        # 连接池最小空闲连接
        min-idle: 1
        # 连接池最大空闲连接
        max-idle: 5
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大空闲连接（使用负值表示没有限制）
        max-wait: -1

  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/test
# 日志记录
#mybatis-plus:
#  configuration:
#    call-setters-on-nulls: true
#    #配置该类sql只会在控制台打印，不会输出到日志文件
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#    #配置该类sql会输出到日志文件，不会输出到控制台
#  #   log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#
#  mapper-locations: classpath*:mapper/*.xml

# 日志记录
logging:
  config: classpath:logback.xml
